monitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('url_monitoring.urls'))
]

url_monitoring/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import url_monitoring.views as monitoring_views

urlpatterns = [
    path(
        '',
        monitoring_views.DashBoardTemplateView.as_view(),
        name='dashboard'
    ),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='registration/login.html'),
        name='login'
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='registration/logout.html'),
        name='logout'
    ),
    path(
        'register/',
        monitoring_views.RegisterTemplateView.as_view(),
        name='register'
    ),
    path(
        'create-url/', monitoring_views.CreateUrlTemplateView.as_view(),
        name='create-url'
    ),
    path(
        'delete-url/<int:pk>/', monitoring_views.UrlDeleteTemplateView.as_view(),
        name='delete-url')
]

url_monitoring/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class URL(models.Model):
    """
    Model for storing user record of URL with interval and response status code
    """
    dt_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Date created',
        help_text='Time of created record'
    )
    dt_updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Date updated',
        help_text='Time of updated record'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField(
        verbose_name='url',
        help_text='Tracked URL'
    )
    status = models.IntegerField(
        blank=True,
        null=True,
        verbose_name='status',
        help_text='Last response HTTP status code from URL'
    )
    interval = models.FloatField(
        verbose_name='interval',
        help_text='Periodic time interval in seconds for Celery task'
    )

    def __str__(self):
        return "Record with url {}".format(self.url)

    def get_absolute_url(self):
        return reverse('dashboard')

url_monitoring/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    """
    Registration form for user
    """
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

url_monitoring/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DeleteView

from url_monitoring.forms import UserRegisterForm
from url_monitoring.models import URL


__all__ = [
    'DashBoardTemplateView',
    'RegisterTemplateView',
    'CreateUrlTemplateView',
    'UrlDeleteTemplateView',
]


class DashBoardTemplateView(LoginRequiredMixin, ListView):
    """
    View display list urls of user
    """

    model = URL
    template_name = 'url_monitoring/dashboard.html'
    content_type = "text/html"
    login_url = 'login'

    def get_queryset(self):
        return URL.objects.filter(user=self.request.user).order_by('dt_created')


class RegisterTemplateView(CreateView):
    """
    View for creating user account
    """
    form_class = UserRegisterForm
    success_url = '/login/'
    template_name = 'registration/register.html'


class CreateUrlTemplateView(LoginRequiredMixin, CreateView):
    """
    View for creating URL record in DB
    """
    model = URL
    fields = ['url', 'interval']
    template_name = 'url_monitoring/url_add.html'
    login_url = '/login/'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class UrlDeleteTemplateView(LoginRequiredMixin, DeleteView):
    """
    View is responsible for deleting URL from DB
    """
    model = URL
    template_name = 'url_monitoring/url_delete.html'
    content_type = "text/html"
    raise_exception = True  # Raise exception when no access instead of redirect to login page
    success_url = '/'

url_monitoring/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% block title %}Monitor{% endblock %}</title>
    {% bootstrap_css %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% bootstrap_javascript jquery='slim' %}

</head>
<body>
<nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url "dashboard" %}">Monitor</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      {% if request.user.is_authenticated %}
    <div class="navbar-nav">
{#        <a class="nav-item nav-link active" href="{% url "dashboard" %}">My URL</a>#}
      <a class="nav-item nav-link active" href="{%  url "create-url" %}">Add URL<span class="sr-only">(current)</span></a>
    </div>
      {% endif %}
  </div>
    <span class="user">
        {% if request.user.is_authenticated %}
            <a href="{% url "logout" %}">Logout</a>
        {% else %}
            <a href="{% url "register" %}">Register</a>
            <a href="{% url "login" %}">Login</a>
        {% endif %}
    </span>
</nav>
<div>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

url_monitoring/templates/url_monitoring/dashboard.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-bordered">
    <thead>
    <tr>
        <th>№</th>
        <th>ID</th>
        <th>URL</th>
        <th>Last Update</th>
        <th>Interval</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {% for record in url_list %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{ record.id }}</td>
            <td><a href="{{ record.url }}">{{ record.url }}</a> </td>
            <td>{{ record.dt_updated }}</td>
            <td>{{ record.interval }}</td>
            <td>{{ record.status }}</td>
            <td><a href="{% url 'delete-url' pk=record.id %}">
                <button type="submit" class="btn btn-outline-danger">Delete</button></a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

url_monitoring/templates/url_monitoring/url_add.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
    Add URL
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="col-5">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-group">
        <button class="btn btn-outline-secondary" type="submit">Add URL</button>
    </div>
    </form>
{% endblock %}

url_monitoring/templates/url_monitoring/url_delete.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block title %}
    Delete URL "{{ url }}"
{% endblock %}

{% block content %}
    <form action="{{ url.get_delete_url }}" method="post">
        {% csrf_token %}
        <div class="form-group my-2 p-2 border col-7">
            <p class="col-5">Are you sure that you want to delete <br>
                <b>"{{ url }}"</b>?</p>
            <a class="btn btn-outline-secondary" href="{{ url.get_absolute_url }}">Cancel</a>

{#            <a href={{ url.get_absolute_url }}><button type="submit" name="button" class="btn btn-outline-secondary">Cancel</button></a>#}
            <button type="submit" name="button" class="btn btn-outline-danger">Delete</button>
        </div>
    </form>

{% endblock %}